service: image-analysis

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - rekognition:DetectLabels
      Resource: "*"

functions:
  image-analysis:
    handler: handler.main
    events:
      - http:
          path: analyse
          method: get
